%%metro title: ProteomeGenerator3
%%metro style: dark
%%metro files: bam_in | BAM/CRAM
%%metro files: fusion_in | Fusion TSV
%%metro file: proteome_out | proteins.fasta
%%metro file: report_out | MultiQC Report
%%metro line: bambu | Bambu | #2196F3
%%metro line: lraa | LRAA | #2db572
%%metro line: stie | StringTie2 | #f5a623
%%metro line: fusion | Fusions (optional) | #e63946 | dashed
%%metro line: qc | Quality Control | #9d4edd
%%metro legend: br

%%metro grid: input_section | 0,0
%%metro grid: preprocessing | 1,0
%%metro grid: assembly_section | 2,0
%%metro grid: curation_section | 3,0
%%metro grid: orf_section | 4,0
%%metro grid: qc_section | 0,1
%%metro grid: proteome_section | 3,1

graph LR

    subgraph input_section [Input & Reference]
        %%metro exit: right | bambu, lraa, stie, qc
        bam_in[ ]
        cram_to_bam[CRAM_TO_BAM]
        samtools_faidx[SAMTOOLS_FAIDX]

        bam_in -->|bambu,lraa,stie,qc| cram_to_bam
        cram_to_bam -->|bambu,lraa,stie,qc| samtools_faidx
    end

    subgraph preprocessing [Preprocessing]
        %%metro entry: left | bambu, lraa, stie
        %%metro exit: right | bambu, lraa, stie
        filter_reads[FILTER_READS]
        bambu_rc[BAMBU_READCLASSES]

        filter_reads -->|bambu| bambu_rc
    end

    subgraph qc_section [Quality Control]
        %%metro direction: RL
        samtools_sort_idx[SAMTOOLS\nSORT/INDEX]
        nanoplot[NanoPlot]
        samtools_stats_qc[SAMTOOLS\nSTATS]
        rseqc_bam[RSeQC]
        picard_rna[PICARD]
        multiqc[MultiQC]
        report_out[ ]

        samtools_sort_idx -->|qc| nanoplot
        samtools_sort_idx -->|qc| samtools_stats_qc
        samtools_sort_idx -->|qc| rseqc_bam
        samtools_sort_idx -->|qc| picard_rna
        nanoplot -->|qc| multiqc
        samtools_stats_qc -->|qc| multiqc
        rseqc_bam -->|qc| multiqc
        picard_rna -->|qc| multiqc
        multiqc -->|qc| report_out
    end

    subgraph assembly_section [Transcript Assembly]
        %%metro entry: left | bambu, lraa, stie
        %%metro exit: right | bambu, lraa, stie
        bambu_asm[BAMBU]
        lraa_asm[LRAA]
        stie_asm[STRINGTIE2]
    end

    subgraph curation_section [GTF Merge & Curation]
        %%metro entry: left | bambu, lraa, stie
        %%metro exit: right | bambu, lraa, stie
        union_merge[LRAA_MERGE\n(union)]
        gffcompare_cur[GFFCOMPARE]
        reannotategtf[REANNOTATEGTF]
        sqanti3_qc[SQANTI3 QC]
        sqanti3_filter[SQANTI3 FILTER]
        sqanti3_rescue[SQANTI3 RESCUE]

        union_merge -->|bambu,lraa,stie| gffcompare_cur
        gffcompare_cur -->|bambu,lraa,stie| reannotategtf
        reannotategtf -->|bambu,lraa,stie| sqanti3_qc
        sqanti3_qc -->|bambu,lraa,stie| sqanti3_filter
        sqanti3_filter -->|bambu,lraa,stie| sqanti3_rescue
    end

    subgraph orf_section [ORF Prediction]
        %%metro entry: left | bambu, lraa, stie
        %%metro exit: bottom | bambu, lraa, stie
        gffread[GFFREAD]
        philosopher_db[PHILOSOPHER\nDATABASE]
        diamond_makedb[DIAMOND\nMAKEDB]
        td_longorf[TRANSDECODER\nLONGORF]
        diamond_blast[DIAMOND\nBLASTP]
        td_predict[TRANSDECODER\nPREDICT]

        gffread -->|bambu,lraa,stie| td_longorf
        philosopher_db -->|bambu,lraa,stie| diamond_makedb
        diamond_makedb -->|bambu,lraa,stie| diamond_blast
        td_longorf -->|bambu,lraa,stie| diamond_blast
        diamond_blast -->|bambu,lraa,stie| td_predict
    end

    subgraph proteome_section [Proteome Assembly]
        %%metro direction: RL
        %%metro entry: right | bambu, lraa, stie
        fusion_in[ ]
        td2fasta[TRANSDECODER2FASTA]
        fusionfasta[FUSIONFASTA]
        cat_cat[CAT_CAT]
        seqkit_rmdup[SEQKIT_RMDUP]
        proteome_out[ ]

        fusion_in -->|fusion| fusionfasta
        fusionfasta -->|fusion| cat_cat
        td2fasta -->|bambu,lraa,stie| cat_cat
        cat_cat -->|bambu,lraa,stie,fusion| seqkit_rmdup
        seqkit_rmdup -->|bambu,lraa,stie,fusion| proteome_out
    end

    %% Inter-section edges
    samtools_faidx -->|bambu,lraa,stie| filter_reads
    samtools_faidx -->|qc| samtools_sort_idx
    filter_reads -->|lraa| lraa_asm
    filter_reads -->|stie| stie_asm
    bambu_rc -->|bambu| bambu_asm
    bambu_asm -->|bambu| union_merge
    lraa_asm -->|lraa| union_merge
    stie_asm -->|stie| union_merge
    sqanti3_rescue -->|bambu,lraa,stie| gffread
    td_predict -->|bambu,lraa,stie| td2fasta
